builds:
  - main: cmd/mocker/main.go
    binary: mocker
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

brew:
  github:
    owner: travisjeffery
    name: homebrew-tap

  commit_author:
    name: travisjeffery
    email: tj@travisjeffery.com

  folder: Formula

  homepage: "https://github.com/travisjeffery"

  description: "Mocker for Go."

